<a href="https://colab.research.google.com/github/HugocamposL3/Inteligencia_Artificial_Senai/blob/main/Ativiade_Inteligencia_Artificial_Regress%C3%A3o_Linear_Usando_LINALG_SOLVE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
MIdade = np.array([[1,1,1,1,1],[20,32,41,49,66]])
MDistancia = np.array([590,410,460,380,350])
print(MIdade)
print(MDistancia)

[[ 1  1  1  1  1]
 [20 32 41 49 66]]
[590 410 460 380 350]


y = distancia e x = idade 
y = alfa + betaX

In [9]:
#Fazendo a transposta da Matriz Idade
MIdadeT = MIdade.transpose()
print(MIdadeT)

[[ 1 20]
 [ 1 32]
 [ 1 41]
 [ 1 49]
 [ 1 66]]


In [13]:
#MIdade * MIdadeT
MTa = np.dot(MIdade,MIdadeT) 
print(MTa)

[[   5  208]
 [ 208 9862]]


In [14]:
#MDistancia * MIdadeT
MTb = np.dot(MDistancia,MIdadeT)
print(MTb)

[ 2190 85500]


In [16]:
#Encontrando meu Alfa e Beta 
X = np.linalg.solve(MTa,MTb)
print(X)

[630.79391333  -4.63446907]


In [25]:
#Fazendo minha matriz de erros 
ME = np.dot(MIdadeT,X)
print(ME)

[538.10453192 482.49090308 440.78068144 403.70492888 324.91895468]


In [30]:
## erro = b - Ax
ME1 = np.subtract(MDistancia,ME)
print(ME1)

[ 51.89546808 -72.49090308  19.21931856 -23.70492888  25.08104532]
